task: 'zju_mocap'
subject: 'train_7'
experiment: 'zju_category_level-pretrain'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.actorsnerf.train_category_level'
  dataset: ['zju_313_train',  'zju_315_train', 'zju_377_train', 'zju_386_train', 'zju_390_train', 'zju_392_train', 'zju_396_train']
  lossweights:
    lpips: 1.0
    mse: 0.2
    mweight_l1: 0.01
#    alpha: 0.0
#    alpha_reg: 0.0
#    flow: 0.0
#    alpha_delta: 0.0
#    xyz_cycle: 0.0
#    eikonal: 0.0

progress:
  dataset_module: 'core.data.actorsnerf.train_category_level'
  dataset: ['zju_313_train',  'zju_315_train', 'zju_377_train', 'zju_386_train', 'zju_390_train', 'zju_392_train', 'zju_396_train']



bgcolor: [0., 0., 0.]
resize_img_scale: 0.5

# reduce the size of patch from 32x32 to 20x20 to fit in a single gpu
patch:
  N_patches: 4
  size: 32      # [Patch] size of patch

num_sub: 7
sub_idx_mapping: {'313': 0, "315": 1,'377': 2, "386": 3, '390': 4, "392": 5,  '396': 6}
use_non_rigid_motions: True
#use_flow_reg: False
use_pose_correction: False
#use_transformation: False
use_cnl_normalize_coords: True
#use_alpha_delta: False
use_enc: True
train_encoder: True
use_bw_cycle_consistency: False
use_data_cross_pose: True
use_data_cross_view: False
use_wandb: False
use_vis_mesh: False
#use_render_mask: False
#render_mask_prob: 1.0
#use_eikonal: False
use_smpl_early_fusion: True
use_smpl_feat: True
use_pixel_feat: True
